#!/usr/bin/env python
# -*- coding:utf-8 -*-


"""
-------------------------------------------------
File Name: SDM
Description :Document description

Author: lenovo
date: 2022/5/25
-------------------------------------------------
Change Activity:
2022/5/25: Description of change
-------------------------------------------------
"""

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
from PIL import Image

from scipy.ndimage import distance_transform_edt as distance
from skimage import segmentation as skimage_seg
from sklearn import preprocessing


import torch


def my_compute_sdf(img_gt):
    img_gt = img_gt.astype(np.uint8)
    # normalized_sdf = np.zeros(out_shape)
    normalized_sdf = np.zeros_like(img_gt)

    posmask = img_gt.astype(np.bool_)

    if posmask.any():
        negmask = ~posmask
        posdis = distance(posmask)
        negdis = distance(negmask)

        boundary = skimage_seg.find_boundaries(posmask, mode="inner").astype(np.uint8)

        sdf = (negdis - np.min(negdis)) / (np.max(negdis) - np.min(negdis)) - \
              (posdis - np.min(posdis)) / (np.max(posdis) - np.min(posdis))
        sdf[boundary == 1] = 0

        normalized_sdf = sdf

    return normalized_sdf


